components:
  parameters:
    ScrollID:
      name: scrollID
      in: path
      description: Scroll ID or unique slug.
      required: true
      schema:
        $ref: "./schemas.yml#/components/schemas/ScrollID"
      examples:
        uuidExample:
          summary: Example UUID
          value: dd486183-17f9-52e0-92a9-45ff579bdeea
        usernameExample:
          summary: Example slug
          value: alarm

    ScrollFields:
      name: fields[scrolls]
      in: query
      description: |
        This optional parameter is a comma-separated list of the attributes
        that you would like to receive back for the scroll requested. Possible
        values include any combination of `slug`, `name`, `description`,
        `body`, `attribution`, `start`, `notes`, `created`, and `updated`.
      schema:
        type: string
      examples:
        summaryExample:
          summary: Fields you might use for a summary, card, or search result
          value: slug,name,description
        datesExample:
          summary: Just the date fields
          value: created,updated
        notes:
          summary: Just the notes
          value: notes
        start:
          summary: Just the number of starting seals
          value: start
