default:
  - active
  - listed
roles:
  anonymous:
    - scale:read
    - user:read
  active:
    - scale:create
    - scale:author:update
    - scale:author:delete
    - user:self:update
    - user:self:destroy
    - role:self:listed:grant
    - role:self:listed:revoke
  listed: []
  admin:
    - '*'