openapi: 3.0.3
info:
  title: Ruins & Revolutions API
  description: |-
    The _Ruins & Revolutions_ API provides programmatic
    access to the catalogue of scales, scrolls, tables,
    and other items that _Ruins & Revolutions_ players
    have developed and shared with the community.
  termsOfService: https://ruinsandrevolutions.com/terms
  contact:
    email: api@ruinsandrevolutions.com
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: '1.0'
servers:
  - url: https://api.ruinsandrevolutions.com/v1/
tags:
  - name: Scales
    description: Operations related to scales.
  - name: Scrolls
    description: Operations related to scrolls.
  - name: Tables
    description: Operations related to random tables.
  - name: Users
    description: Operations related to users and user records.
  - name: Authentication
    description: Authentication
  - name: Accounts
    description: The OAuth 2.0 provider accounts that a user can associate with her account.
paths:
  /accounts:
    $ref: "../collections/accounts/docs/path-collection.yml"
  /accounts/{provider}:
    $ref: "../collections/accounts/docs/path-resource.yml"
  /auth/tokens:
    $ref: "../collections/auth/tokens/docs/path-collection.yml"
  /auth/providers:
    $ref: "../collections/auth/providers/docs/path-collection.yml"
  /scales:
    $ref: "../collections/scales/docs/path-collection.yml"
  /scales/{scaleId}:
    $ref: "../collections/scales/docs/path-resource.yml"
  /scrolls:
    $ref: "../collections/scrolls/docs/path-collection.yml"
  /scrolls/{scrollId}:
    $ref: "../collections/scrolls/docs/path-resource.yml"
  /tables:
    $ref: "../collections/tables/docs/path-collection.yml"
  /tables/{tableId}:
    $ref: "../collections/tables/docs/path-resource.yml"
  /users/{userId}:
    $ref: "../collections/users/docs/path-resource.yml"
  /users/{userId}/roles/{role}:
    $ref: "../collections/users/roles/docs/path-resource.yml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    $ref: "./schemas.yml#/components/schemas"
  parameters:
    $ref: "./parameters.yml#/components/parameters"
