name: ruinsandrevolutions_api_test_workflow

volumes:
  test_db: {}

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5433:5432
    volumes:
      - test_db:/var/lib/postgresql/data
    env_file:
      - ./test-workflow.postgres.env

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8001:8000
    env_file:
      - ./test-workflow.postgres.env
      - ./test-workflow.api.env
    depends_on:
      - postgres

  tests:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: tests
    env_file:
      - ./test-workflow.postgres.env
      - ./test-workflow.api.env
    entrypoint: >
      sh -c "
      ./wait-for-it.sh api:8001 --timeout=30 &&
      deno test --allow-net --allow-env --allow-read --allow-import --trace-leaks"
